imports:
    - { resource: '@SyliusB2BKitPlugin/config/indexes/*' }

parameters:
    bitbag_es_pagination_available_page_limits: [ 9, 18, 36 ]
    bitbag_es_pagination_default_limit: 9
    bitbag_es_fuzziness: AUTO

twig:
    globals:
        bitbag_es_pagination_available_page_limits: "%bitbag_es_pagination_available_page_limits%"

fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
